---
# Global defaults
env: wtf
region: us-west-2
ansible_connection: community.aws.aws_ssm
ansible_aws_ssm_bucket_name: "rch-ansible-ssm-{{ env }}-{{ region|default('us-east-1') }}"
ansible_aws_ssm_region: "{{ region|default('us-east-1') }}"
ansible_remote_tmp: /tmp
ansible_shell_executable: /bin/bash
